
export const giversNames = [
    "Abiodun Agbonsalo",
    "Abiola Daramola",
    "Adedayo Adesulu",
    "Adepeju Akere",
    "Adesola Ayobiojo",
    "Alice Bangura",
    "Anne Kimani",
    "Anthony Woghiren",
    "Arline Laverdure",
    "Bangee and Company",
    "Bintu M Samah",
    "Bridget Arguidese",
    "Chiazoka Chukwuma - osuji",
    "Chioma Okafor",
    "Daniel O.Adigun",
    "David Oseji",
    "Desmond P Coker",
    "Eagle Gutters Corp",
    "Ebubechukwu I Okafor",
    "Edith Delali",
    "Edward Ofurie",
    "Ekwunife Somto",
    "Ekwunife Ugochukwu",
    "Elizabeth Achayo",
    "Emmanuel Ilori",
    "Eseosa Okunmwendia",
    "Eucharia Obianeli",
    "Eucharia N Scott",
    "Evelyn Sakwe",
    "Everlyne Njeru",
    "Festus Igharo",
    "Florence Namuyimbwa",
    "foluke ogbodo",
    "Frances Health Services",
    "Frances Igiebor",
    "Francisca Ojei",
    "Frederick O McLemore",
    "Frederick Otokunrin",
    "Helen King",
    "ibeyemi Oyebanjo",
    "Irhene Kelvin Osagie",
    "jackie miwanda",
    "Jacob A Bello",
    "Jane Muchene",
    "Jenneh R Coker",
    "John Igoche Obute",
    "John N Mbuthia",
    "John Okafor Kalu Olu",
    "Joshua Omoregbee",
    "Joy Chikezie Meregini",
    "Joy EE Aigbogun",
    "Kelvin Osagie",
    "Kenneth O Agbonhabonse",
    "Koffi Gakpe",
    "Mabel Ebhohon",
    "Malcolm Ebhohon",
    "Mamy T Madiyamuanzadika",
    "Marcia A Hinds",
    "Margaret Omo - Osagie",
    "Marie N Akem",
    "Marie Koroma",
    "Martins E Igberaese",
    "Mary Kemeh",
    "Mary Ochije",
    "Mary Wambui",
    "Melissa Adigun",
    "Melissa C.Lee",
    "Mercy Ochije",
    "Mercy Omosefe",
    "Michael Monwuba",
    "Ngozi Anyika",
    "Nicole Njoroge",
    "Nnamdi Udemagwuna",
    "Nosataba C.Laurent",
    "Nosayaba C.Ogbebor",
    "nwanne Agbai",
    "Nwobilo Nweke",
    "Oduwa Osagiede",
    "Olabanji Lawal",
    "Olanrewaju Otukoya",
    "Olayinka Oluyomi Ogunpola",
    "Olufunke A Sowemimo",
    "Olukayode S Anifowose",
    "Oluwadamilola A Adeyemi",
    "Oluwafisa Ogunkoya",
    "Oluwaseun Omofoye",
    "Oyin F Ateme",
    "Pamela Iloabachie",
    "Patrick Gitemi",
    "Peter O Omo - Osagie",
    "Queenta E Etta",
    "Rahel Sobo",
    "Raphael Arhuidese",
    "Robinson Olabhie",
    "Ruben Santiago",
    "Samela Wariebi",
    "Shirley Gakpetor",
    "Sidney Ngebeh",
    "Solomon Nwachukwu",
    "Sosthene zinsouply",
    "Stella Ekwunife",
    "Taiwo Adefiyiju",
    "Taylor Rochell",
    "Teresia Kigathi",
    "Teresia W Njenga",
    "Veronica Nzemwa",
    "Victor O.Omorotionmwan",
    "Vivian Onaiwu",
    "Vivian Thomas",
    "Winnie Waiganjo",
    "Winston Mbajekwe",
    "Yanick Lahens",
    "yvonne Patricia Gordon",
    "Rochell W GD Taylor",
    "Rosemary W Kahara",
    "Augusta M Shorrow",
    "Chukwuma T Osuji",
    "Ebuwa Igbinedion",
    "Geneva Hazel McLemore",
    "Tonisha N Gracia",
    "Wonser & Tarwo",
    "Justina E Iyere",
    "Farah Correia",
    "Edward Nweke",
    "Dba Otaliems Services",
    "Tubolayefa Jennifer Asei",
    "Bank of Canton",
    "Ritah Namigadde",
    "Lieoma V.McAnthony",
    "Dickson & Jyawe",
    "Joy Ighile",
    "Jonathan Tay",
    "Rosemond Asiedu",
    "Babette Kini Lendo",
    "Oladeinde agoro",
    "Rent reimbursement",
    "Catherine Nganga",
    "John Correia",
    "Annymonous",
    "Ruby Isioma Okechukwu",
    "Elen Gevorgyan",
    "Poland Spring Reimbursement",
    "Check Expenses Account"
];

giversNames.sort()